- content/quick_start/try_opennebula/opennebula_on-prem_with_minione/deploy_opennebula_onprem_with_minione.md
> M #-: MinioONE command and output

- README.md
Update the Readme with the contents of the documentation contribution guide.
> M #-: Update Readme file

- content/software/release_information/release_notes_enterprise/resolved_issues_701.md
This PR adds documentation on removing sensitive data from fireedge.log.
Applies to branch one-7.0-maintenance
> Resolved issues 7.0 - maintenance

- content/software/release_information/release_notes_enterprise/resolved_issues_701.md
- Add issue [#6803](https://github.com/OpenNebula/one/issues/6803) on resolved issues for version 7.0.1
>  B OpenNebula/one#6803: Update resolved issues for 7.0.1

- content/software/release_information/release_notes_enterprise/resolved_issues_701.md
> B OpenNebula/one#7146: Update resolved issues

- content/product/cloud_system_administration/resource_monitoring/forecast.md
Wrong path for forecast.conf file
> M #-: Wrong path for forecast.conf file

- content/quick_start/try_opennebula/opennebula_on-prem_with_minione/deploy_opennebula_onprem_with_minione.md
Replace 6.99 with 7.0 in miniONE output
> M #-: Replace 6.99 string

- publish/publish.rb
- [ x ] master
- [ x ] one-7.0
<hr>
> M #-: Fix cleanup of old builds on publish.rb

- content/product/apps-marketplace/public_marketplaces/overview.md
- content/software/release_information/release_notes_70/known_issues.md
- dicts/OpenNebula.dic
- Style review of new paragraphs in Known Issues
- Add word to dictionary
- Fix typo
<hr>
> M #-: Style review of Known Issues

- content/product/cluster_configuration/storage_system/local_ds.md
- content/software/release_information/release_notes_enterprise/resolved_issues_701.md
> F OpenNeubla/one#6373: Include release notes and change defaults

- content/software/release_information/release_notes_enterprise/resolved_issues_701.md
* Update resolved issues with OpenNebula/one#7138
<hr>
> M OpenNebula/one#7138: Update resolved issues

- content/software/release_information/release_notes_70/known_issues.md
* Adds OpenNebula/one#7173 to known issues.
<hr>
> B OpenNebula/one#7173: Update known issues

- content/software/release_information/release_notes_enterprise/resolved_issues_701.md
Add issue [#7082](https://github.com/OpenNebula/one/issues/7082) on resolved issues for version 7.0.1
> B OpenNebula/one#7082: Update resolved issues for 7.0.1

- content/software/release_information/release_notes_enterprise/resolved_issues_701.md
Update resolved issues for 7.0.1
<hr>
> B OpenNebula/one#7136: Style bug with Disable animations switch

- content/software/release_information/release_notes_enterprise/resolved_issues_701.md
* Add OpenNebula/one#7062 to resolved issues.
<hr>
> M OpenNebula/one#7062: Update resolved issues

- content/software/release_information/release_notes_enterprise/resolved_issues_701.md
Closes OpenNebula/one#7195
<hr>
> B OpenNebula/one#7195: Update resolved issues

- content/product/control_plane_configuration/large-scale_deployment/fireedge_for_large_deployments.md
Should go also to doc repo to one-6.10 branch - I don't have permissions to push a branch for a PR
<hr>
> B OpenNebula/one#7171: Add missing semicolon to nginx example

- content/solutions/certified_hw_platforms/ampere_opennebula/_index.md
- content/solutions/hosted_cloud_providers/ionos_opennebula/_index.md
To make the Solutions parent pages consistend and provide a good example for future contribuions of new hw solutions and hosted cloud providers, we remove the description/abstract from the parent page.
Tested locally with `hugo server`
> F OpenNebula/one#7219: remove abstracts from Solutions parent pages

- content/software/release_information/release_notes_enterprise/resolved_issues_701.md
Updates solved issues for 7.0.1 to add Veeam concurrency fixes
<hr>
> F OpenNebula/engineering#444: Add Veeam concurrency to solved issues 

- content/product/operation_references/configuration_references/template.md
- content/product/virtual_machines_operation/virtual_machine_definitions/vm_templates.md
Docs for https://github.com/OpenNebula/one/issues/5892.
<hr>
> F #5892: Add TPM documentation

- content/product/operation_references/opennebula_services_configuration/oned.md
- content/software/installation_process/build_from_source_code/compile.md
- content/software/release_information/release_notes_70/platform_notes.md
> M #-: Add new compile param, drop xmlrpc-c old notes

- layouts/partials/sidebar-tree.html
PR to remove the search/filter bar from the list of contents. The search bar is replaced by a relevant title.
<hr>
> B OpenNebula/website#7232: Removed duplicated search bar

- content/integrations/backup_extensions/veeam.md
- content/software/release_information/release_notes_enterprise/resolved_issues_701.md
Added information on the latest Veeam integration updates, mainly the LVM-thin incremental backup support and the parallelism improvements.
<hr>
> M #-: Veeam LVM incrementals and parallelism advice

- content/software/installation_process/automatic_installation_with_onedeploy/one_deploy_tutorial_local_ds.md
- content/software/installation_process/automatic_installation_with_onedeploy/one_deploy_tutorial_shared_ds.md
- content/software/installation_process/build_from_source_code/compile.md
- content/software/installation_process/manual_installation/_index.md
- content/software/installation_process/manual_installation/database.md
- content/software/installation_process/manual_installation/front_end_installation.md
- content/software/installation_process/manual_installation/kvm_node_installation.md
- content/software/installation_process/manual_installation/lxc_node_installation.md
- content/software/installation_process/manual_installation/opennebula_repository_configuration.md
- content/software/migration_from_vmware/import_ova.md
- content/software/migration_from_vmware/oneswap.md
- content/software/migration_from_vmware/overview.md
- content/software/release_information/release_notes_community/what_is.md
- content/software/release_information/release_notes_enterprise/what_is.md
- content/software/upgrade_process/configuration_management_ee/appendix.md
- content/software/upgrade_process/upgrade_guide/upgrading_federation.md
- content/software/upgrade_process/upgrade_guide/upgrading_ha.md
- content/software/upgrade_process/upgrade_guide/upgrading_single.md
Book: Software
Updated sidebar titles and added Overview
<hr>
> F OpenNebula/one#7243: Updated sidebar titles and added Overview

- content/software/release_information/release_notes_enterprise/resolved_issues_701.md
> B OpenNebula/one#7251: Update resolved issues

- content/software/release_information/release_notes_enterprise/resolved_issues_701.md
Updates resolved issues for 7.0.1.
<hr>
> B OpenNebula/one#7239: update resolved issues

- content/product/cluster_configuration/backup_system/veeam.md
Removed outdated Veeam limitations.
<hr>
> M #-: Removed outdated limitations

- content/software/release_information/release_notes_enterprise/resolved_issues_701.md
Fixed Security Group Rule Description for IPs
<hr>
> B OpenNebula/one#7186 fix security group rule description

- content/product/cluster_configuration/storage_system/local_ds.md
Improve local DS requirements docs
<hr>
> M #-: improve local DS requirements docs

- content/software/release_information/release_notes_enterprise/resolved_issues_701.md
* Add OpenNebula/one#7212 to resolved issues
<hr>
> M OpenNebula/one#7212: Update resolved issues
